In [5]:
import cv2
import sys
import numpy as np
#%matplotlib inline
from matplotlib import pyplot as plt

In [3]:
car_cascade = cv2.CascadeClassifier('../data/cars.xml')

cap = cv2.VideoCapture("../data/KM84.mp4")
while not cap.isOpened():
    cap = cv2.VideoCapture("../data/KM84.mp4")
    cv2.waitKey(1000)
    print "Wait for the header"


In [4]:
# 8fps
num_fps = 8

pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
features = []

num_of_object = []
detected_object = []

# cam84
xlane1_start = 355
ylane1_start = 263
xlane1_end = 443
ylane1_end = 540

xlane2_start = 373
ylane2_start = 263
xlane2_end = 543
ylane2_end = 536

xlane3_start = 389
ylane3_start = 259
xlane3_end = 642
ylane3_end = 538

xlane4_start = 412
ylane4_start = 270
xlane4_end = 713
ylane4_end = 501

while True:
    ncars = 0
    flag, frame = cap.read()
    if pos_frame % num_fps == 0:
        if flag:
            # The frame is ready and already captured
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            cars = car_cascade.detectMultiScale(gray, 1.1, 1)
            cv2.line(frame, (xlane1_start, ylane1_start), (xlane1_end, ylane1_end), (0,255,0), 1)
            cv2.line(frame, (xlane2_start, ylane2_start), (xlane2_end, ylane2_end), (0,255,0), 1)
            cv2.line(frame, (xlane3_start, ylane3_start), (xlane3_end, ylane3_end), (0,255,0), 1)
            cv2.line(frame, (xlane4_start, ylane4_start), (xlane4_end, ylane4_end), (0,255,0), 1)
#             cv2.imwrite("frame1.jpg", frame)
#             sys.exit()

            
            #tentukan, object cars masuk lane mana
            lane = 0
            for (x, y, w, h) in cars:
                if x >= xlane1_start and x < xlane2_start:
                    lane = 1
                elif x >= xlane2_start and x < xlane3_start:
                    lane = 2
                elif x >= xlane3_start and x < xlane4_start:
                    lane = 3
#                 cars[4] = lane
            np.insert(cars, 4, lane)
            detected_object.append(cars) # untuk menghitung jarak antar object
#             num_of_object.append([len(cars)])
            # cars : detected object
            print cars
            num_of_object = len(cars)
            print 'num of object : ' + str(num_of_object)
            
            # Draw border
            for (x, y, w, h) in cars:
                cv2.rectangle(frame, (x,y), (x+w,y+h), (0,0,255), 2)
                ncars = ncars + 1
                
            #ketika detected carsnya ada di range value x ... (pada lane ke sekian, sampai ia di sumbu y yang maksimal, dan menghilang, hitung berapa lama ia ada di frame) -> velocity
    #         plt.figure(figsize=(10,20))
            # plt.imshow(frame)

            # find the speed

            cv2.imshow('video', frame)
            pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
            print str(pos_frame)+"frames"
            print "ncars : " + str(ncars)
            
        else:
            # The next frame is not ready, so we try to read it again
            cap.set(cv2.cv.CV_CAP_PROP_POS_FRAMES, pos_frame-1)
            print "frame is not ready"
            # It is better to wait for a while for the next frame to be ready
            cv2.waitKey(1000)
    else:
        pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
    
    if cv2.waitKey(10) == 27:
        break
    if cap.get(cv2.CAP_PROP_POS_FRAMES) == cap.get(cv2.CAP_PROP_FRAME_COUNT):
        # If the number of captured frames is equal to the total number of frames,
        # we stop
        break
        
# features[0] = num_of_object
# features[1] = num_of_object

[[118  59  21  21]
 [  2  61  32  32]
 [273 289  38  38]]
num of object : 3
1.0frames
ncars : 3
[[118  59  21  21]
 [  2  61  32  32]]
num of object : 2
9.0frames
ncars : 2
[[ 2 61 32 32]]
num of object : 1
17.0frames
ncars : 1
[[  2  61  32  32]
 [112  48  39  39]]
num of object : 2
25.0frames
ncars : 2
[[  2  61  32  32]
 [130 349  37  37]]
num of object : 2
33.0frames
ncars : 2
[[  2  61  32  32]
 [ 82  20  80  80]
 [178 428  84  84]]
num of object : 3
41.0frames
ncars : 3
[[118  59  21  21]
 [  2  61  32  32]
 [207 391  64  64]]
num of object : 3
49.0frames
ncars : 3
[[118  59  21  21]
 [  2  61  32  32]
 [295 388  39  39]
 [226 361  61  61]]
num of object : 4
57.0frames
ncars : 4
[[118  59  21  21]
 [243 360  22  22]
 [  2  61  32  32]
 [299 356  34  34]
 [199  42  39  39]]
num of object : 5
65.0frames
ncars : 5
[[118  59  21  21]
 [  2  61  32  32]
 [251 327  45  45]]
num of object : 3
73.0frames
ncars : 3
[[ 2 61 32 32]]
num of object : 1
81.0frames
ncars : 1
[[  2  61  32  32]


[[82 20 80 80]]
num of object : 1
681.0frames
ncars : 1
[[666 281  21  21]]
num of object : 1
689.0frames
ncars : 1
[[666 281  21  21]]
num of object : 1
697.0frames
ncars : 1
[[666 281  21  21]]
num of object : 1
705.0frames
ncars : 1
[[108  44  45  45]]
num of object : 1
713.0frames
ncars : 1
[[82 20 80 80]]
num of object : 1
721.0frames
ncars : 1
[[108  44  45  45]]
num of object : 1
729.0frames
ncars : 1
[[108  44  45  45]]
num of object : 1
737.0frames
ncars : 1
[[108  44  45  45]]
num of object : 1
745.0frames
ncars : 1
[[82 20 80 80]]
num of object : 1
753.0frames
ncars : 1
[[430 322  41  41]
 [412 306  66  66]
 [ 82  20  80  80]]
num of object : 3
761.0frames
ncars : 3
[[441 338  49  49]
 [108  44  45  45]]
num of object : 2
769.0frames
ncars : 2
[[441 338  49  49]
 [108  44  45  45]]
num of object : 2
777.0frames
ncars : 2
[[441 338  49  49]
 [108  44  45  45]]
num of object : 2
785.0frames
ncars : 2
[[441 338  49  49]
 [108  44  45  45]]
num of object : 2
793.0frames
ncars : 

IndexError: index 4 is out of bounds for axis 0 with size 0

In [5]:
type(cars)

numpy.ndarray

In [15]:
l = [1,2,3,4,5]
average(l)

NameError: name 'average' is not defined